export const routes = {
  home: "/",
  success: "/checkout/success",
  login: "/auth/login",
  signup: "/auth/signup",
  summary: "/checkout/summary",
  createUser: "/api/auth/createUser",
  dashboardEnd: "/api/dashboard/",
  addProduct: "/api/dashboard/add-product",
  statistics: "api/dashboard/statistics",
  dashboard: "/dashboard",
  dashboardNewProduct: "/dashboard/new-product",
  dashboardDelivery: "/dashboard/delivery",
  dashboardProductsList: "/dashboard/products-list",
};
